version: "3.3"

services:
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env.prod
    environment:
      - TZ=Europe/Moscow
    volumes:
      - ./:/app:rw
    ports:
      - "80:80"
      - "443:443"